server:
  port: 8080

# 数据库数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 2279948211zyf
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: afe1.pojo   #   别名
  mapper-locations: classpath:/mybatis/*.xml   #   xml文件


logging:
  file:
    name: log/log.log
  level:
    root: info
    afe1: debug



